apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${project.artifactId}-secret-v${parsedVersion.majorVersion}
  namespace: {{env_name}}
stringData:
  version: ${project.artifactId}-${project.version}
  xordbPassword: {{secret.xor_icp_ms.xordbPassword}}
  iedbPassword: {{secret.xor_icp_ms.iedbPassword}}
  xorMsMongoDbPassword: {{secret.xor_icp_ms.xorMsMongoDbPassword}}