apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ${project.artifactId}
  name: ${project.artifactId}
  namespace: {{env_name}}
spec:
  serviceName: ${project.artifactId}
  replicas: ${msMinReplicas}
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: ${project.artifactId}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
        - name: ${xorDockerRegistry}
      containers:
        - name: ${project.artifactId}
          image: ${xorDockerImage}
          imagePullPolicy: Always
          ports:
            - containerPort: ${msContainerPort}
          resources:
            limits:
              cpu: ${msCPULimit}
              memory: ${msMemLimit}
            requests:
              cpu: ${msCPURequest}
              memory: ${msMemRequest}
          env:
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MS_PROFILE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            #secrets
            - name: xor_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}-secret-v${parsedVersion.majorVersion}
                  key: xordbPassword
            - name: IE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}-secret-v${parsedVersion.majorVersion}
                  key: iedbPassword
            - name: Mongo_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}-secret-v${parsedVersion.majorVersion}
                  key: xorMsMongoDbPassword
          volumeMounts:
            - name: xor-efs
              mountPath: /data
      volumes:
        - name: xor-efs
          persistentVolumeClaim:
            claimName: xor-data